spring:
  application:
    name: circleguard-file-service

# Placeholder for S3/MinIO configuration if needed later
# aws:
#   s3:
#     endpoint: http://localhost:9000
#     access-key: minioadmin
#     secret-key: minioadmin

server:
  port: 8085

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

  tracing:
    sampling:
      probability: ${SAMPLING_PROBABILITY:1.0}
  otlp:
    tracing:
      endpoint: ${JAEGER_OTLP_ENDPOINT:http://jaeger-collector.stage.svc.cluster.local:4318/v1/traces}
