global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'circleguard-services'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'auth-service:8180'
          - 'identity-service:8083'
          - 'promotion-service:8088'
          - 'notification-service:8082'
          - 'form-service:8086'
          - 'gateway-service:8087'
          - 'dashboard-service:8084'
          - 'file-service:8085'
