package com.circleguard.promotion.service;

import com.circleguard.promotion.model.graph.CircleNode;
import com.circleguard.promotion.repository.graph.CircleNodeRepository;
import com.circleguard.promotion.repository.graph.UserNodeRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.List;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class AutoCircleServiceTest {

    @Mock
    private UserNodeRepository userRepository;

    @Mock
    private CircleNodeRepository circleRepository;

    @Mock
    private CircleService circleService;

    private AutoCircleService autoCircleService;

    @BeforeEach
    void setUp() {
        autoCircleService = new AutoCircleService(userRepository, circleRepository, circleService);
    }

    @Test
    void evaluateEncounters_callsCircleServiceWhenThresholdExceeded() {
        String a1 = "user-1";
        String a2 = "user-2";

        when(userRepository.getCumulativeEncounterDuration(a1, a2)).thenReturn(4000L);
        when(circleRepository.findCommonCircles(a1, a2)).thenReturn(List.of());
        when(circleRepository.save(any(CircleNode.class))).thenAnswer(i -> i.getArgument(0));

        autoCircleService.evaluateEncounter(a1, a2);

        verify(circleService).joinCircle(eq(a1), anyString());
        verify(circleService).joinCircle(eq(a2), anyString());
        verify(circleRepository).save(any(CircleNode.class));
    }

    @Test
    void evaluateEncounters_doesNotCallCircleServiceWhenUnderThreshold() {
        String a1 = "user-1";
        String a2 = "user-2";

        when(userRepository.getCumulativeEncounterDuration(a1, a2)).thenReturn(100L);

        autoCircleService.evaluateEncounter(a1, a2);

        verify(circleRepository, never()).findCommonCircles(anyString(), anyString());
        verify(circleRepository, never()).save(any(CircleNode.class));
        verify(circleService, never()).joinCircle(anyString(), anyString());
    }

    @Test
    void evaluateEncounters_doesNotCallCircleServiceWhenDurationIsNull() {
        String a1 = "user-1";
        String a2 = "user-2";

        when(userRepository.getCumulativeEncounterDuration(a1, a2)).thenReturn(null);

        autoCircleService.evaluateEncounter(a1, a2);

        verify(circleRepository, never()).findCommonCircles(anyString(), anyString());
        verify(circleRepository, never()).save(any(CircleNode.class));
        verify(circleService, never()).joinCircle(anyString(), anyString());
    }

    @Test
    void evaluateEncounters_skipsWhenAlreadyInAutoCircle() {
        String a1 = "user-1";
        String a2 = "user-2";
        CircleNode existingAutoCircle = CircleNode.builder()
                .isAutoGenerated(true)
                .build();

        when(userRepository.getCumulativeEncounterDuration(a1, a2)).thenReturn(4000L);
        when(circleRepository.findCommonCircles(a1, a2)).thenReturn(List.of(existingAutoCircle));

        autoCircleService.evaluateEncounter(a1, a2);

        verify(circleRepository, never()).save(any(CircleNode.class));
        verify(circleService, never()).joinCircle(anyString(), anyString());
    }

    @Test
    void evaluateEncounters_returnsEarlyWhenEitherParamIsNull() {
        autoCircleService.evaluateEncounter(null, "user-2");
        autoCircleService.evaluateEncounter("user-1", null);
        autoCircleService.evaluateEncounter(null, null);

        verify(userRepository, never()).getCumulativeEncounterDuration(anyString(), anyString());
    }

    @Test
    void evaluateEncounters_returnsEarlyWhenParamsAreEqual() {
        autoCircleService.evaluateEncounter("same-user", "same-user");

        verify(userRepository, never()).getCumulativeEncounterDuration(anyString(), anyString());
    }

    @Test
    void evaluateEncounters_handlesExceptionsGracefully() {
        String a1 = "user-1";
        String a2 = "user-2";

        when(userRepository.getCumulativeEncounterDuration(a1, a2)).thenThrow(new RuntimeException("DB error"));

        assertThrows(RuntimeException.class, () -> autoCircleService.evaluateEncounter(a1, a2));
    }
}
